#ifndef ADR_H
#define ADR_H

#define CONV1_NUM_FILTERS 32
#define CONV1_NUM_CHANNELS 3
#define CONV1_FILTER_SIZE 3
#define CONV1_NUM_BIAS 32
#define CONV1_PICTURE_SIZE 32
#define CONV1_PADDED_PICTURE_SIZE 34

#define CONV2_NUM_FILTERS 32
#define CONV2_NUM_CHANNELS 32
#define CONV2_FILTER_SIZE 3
#define CONV2_NUM_BIAS 32
#define CONV2_PICTURE_SIZE 16
#define CONV2_PADDED_PICTURE_SIZE 18

#define CONV3_NUM_FILTERS 64
#define CONV3_NUM_CHANNELS 32
#define CONV3_FILTER_SIZE 3
#define CONV3_NUM_BIAS 64
#define CONV3_PICTURE_SIZE 8
#define CONV3_PADDED_PICTURE_SIZE 10

#define NUM_OF_PICTURES 10
#define PICTURE_SIZE 32
#define PICTURE_NUM_CHANNELS 3 
#define NUM_OF_LABELS 10

#define WEIGHTS_NUM_OF_PARAMETARS   CONV1_NUM_FILTERS*CONV1_FILTER_SIZE*CONV1_FILTER_SIZE*CONV1_NUM_CHANNELS + CONV2_NUM_FILTERS*CONV2_FILTER_SIZE*CONV2_FILTER_SIZE*CONV2_NUM_CHANNELS + CONV3_NUM_FILTERS*CONV3_FILTER_SIZE*CONV3_FILTER_SIZE*CONV3_NUM_CHANNELS
#define BIAS_NUM_OF_PARAMETARS      CONV1_NUM_FILTERS+CONV2_NUM_FILTERS+CONV3_NUM_FILTERS
#define PICTURE_START_ADDRESS_RAM   BIAS_NUM_OF_PARAMETARS+WEIGHTS_NUM_OF_PARAMETARS

#define CONV1_WEIGHTS_NUM           CONV1_NUM_FILTERS*CONV1_FILTER_SIZE*CONV1_FILTER_SIZE*CONV1_NUM_CHANNELS
#define CONV2_WEIGHTS_NUM           CONV2_NUM_FILTERS*CONV2_FILTER_SIZE*CONV2_FILTER_SIZE*CONV2_NUM_CHANNELS
#define CONV3_WEIGHTS_NUM           CONV3_NUM_FILTERS*CONV3_FILTER_SIZE*CONV3_FILTER_SIZE*CONV3_NUM_CHANNELS


#define CONV2_HALF_WEIGHTS          CONV2_WEIGHTS_NUM / 2
#define CONV3_SPLIT_WEIGHTS         CONV3_WEIGHTS_NUM / 4


#define CONV1_BIAS_START    0
#define CONV1_BIAS_END      CONV1_BIAS_START + CONV1_NUM_BIAS - 1

#define CONV2_BIAS_START    CONV1_BIAS_END + 1
#define CONV2_BIAS_END      CONV2_BIAS_START + CONV2_NUM_BIAS - 1

#define CONV3_BIAS_START    CONV2_BIAS_END + 1
#define CONV3_BIAS_END      CONV3_BIAS_START + CONV3_NUM_BIAS - 1


#define CONV1_WEIGTS_START  CONV3_BIAS_END + 1
#define CONV1_WEIGTS_END    CONV1_NUM_FILTERS*CONV1_NUM_CHANNELS*CONV1_FILTER_SIZE*CONV1_FILTER_SIZE - 1

#define CONV2_WEIGTS_START  CONV1_WEIGTS_END + 1
#define CONV2_WEIGTS_END    CONV2_WEIGTS_START + CONV2_NUM_FILTERS*CONV2_NUM_CHANNELS*CONV2_FILTER_SIZE*CONV2_FILTER_SIZE - 1

#define CONV3_WEIGTS_START  CONV2_WEIGTS_END + 1
#define CONV3_WEIGTS_END    CONV3_WEIGTS_START + CONV3_NUM_FILTERS*CONV3_NUM_CHANNELS*CONV3_FILTER_SIZE*CONV3_FILTER_SIZE - 1


#define PICTURE_1_START     CONV3_WEIGTS_END + 1
#define PICTURE_1_END       PICTURE_1_START + PICTURE_NUM_CHANNELS*PICTURE_SIZE*PICTURE_SIZE - 1


#endif